services:
    napcat:
        env_file:
            - .env
        ports:
            - 3000:3000
            - 3001:3001
            - 6099:6099
        container_name: napcat
        restart: always
        image: mlikiowa/napcat-docker:latest
        volumes:
            - ./data/napcat/QQ:/app/.config/QQ
            - ./data/napcat/config:/app/napcat/config
            - ./data/napcat/plugins:/app/napcat/plugins
    ncm-api:
        container_name: ncm-api
        restart: always
        image: binaryify/netease_cloud_music_api:latest
        ports:
            - 3010:3000
    mimi:
        build: .
        container_name: mimi
        env_file:
            - .env
        restart: unless-stopped
        volumes:
            - ./data/mini/plugins/apex/data:/app/plugins/apex/data
            - ./data/mini/plugins/yasuo/data:/app/plugins/yasuo/data
        depends_on:
            napcat:
                condition: service_started
            ncm-api:
                condition: service_started
